  CREATE VIEW View1 (Average_Salary, EmployeeId) AS (
  SELECT SUM(S.Amount)/COUNT(S.Amount), S.EmployeeId FROM Employee E, Salary S WHERE (E.EmployeeId = S.EmployeeId) GROUP BY S.EmployeeId
);

CREATE VIEW View2 (Passed_Interview_Rounds, ApplicantId) AS (
  SELECT COUNT(*), X.POTENTIALEMPLOYEEID FROM 
    (SELECT DISTINCT I.INTERVIEWID, PE.POTENTIALEMPLOYEEID 
       FROM PotentialEmployee PE, Interview I 
      WHERE (I.APPLICANTID = PE.POTENTIALEMPLOYEEID)) X, Interview_Grade IG 
   WHERE IG.INTERVIEWID = X.INTERVIEWID AND IG.GRADE > 60 GROUP BY X.POTENTIALEMPLOYEEID
);

CREATE VIEW View3 (Number_Of_Items, ProductType) AS (
  SELECT COUNT(*), P.PRODUCTTYPE FROM PRODUCT P GROUP BY P.PRODUCTTYPE
);

CREATE VIEW View4 (Part_Purchase_Cost, Product) AS (
  SELECT SUM(X.PRICE * X.QUANTITY), X.PRODUCTTYPE 
   FROM (SELECT DISTINCT PART.PRICE, PP.Quantity, PRODUCT.PRODUCTTYPE 
           FROM PRODUCT PRODUCT, PART PART, PRODUCT_PARTS PP 
          WHERE (PP.PRODUCTID = PRODUCT.PRODUCTID AND PART.PARTID = PP.PARTID)) X 
   GROUP BY X.PRODUCTTYPE
);